apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{.Values.service.selector}}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.targetport}}
